subdir-ccflags-$(CONFIG_ARCH_TEGRA) += -Iarch/arm/mach-tegra

obj-$(CONFIG_MACH_ASUSTEK) += devices_asustek.o
obj-$(CONFIG_ASUSTEK_PCBID) += asustek-pcbid.o

CFLAGS_devices_asustek.o += -Idrivers/staging/android
